spring:
  application:
    name: ZUUL-SERVER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
server:
  port: 8180
ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 60000
