eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
